# TCL File Generated by Component Editor 22.1
# Wed Dec 06 11:59:42 JST 2023
# DO NOT MODIFY


# 
# pio_source "pio_source" v1.0
#  2023.12.06.11:59:42
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pio_source
# 
set_module_property DESCRIPTION ""
set_module_property NAME pio_source
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pio_source
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pio_source
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pio_source.sv SYSTEM_VERILOG PATH hdl/pio_source.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL pio_source
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file pio_source.sv SYSTEM_VERILOG PATH hdl/pio_source.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point pio_in
# 
add_interface pio_in conduit end
set_interface_property pio_in associatedClock ""
set_interface_property pio_in associatedReset ""
set_interface_property pio_in ENABLED true
set_interface_property pio_in EXPORT_OF ""
set_interface_property pio_in PORT_NAME_MAP ""
set_interface_property pio_in CMSIS_SVD_VARIABLES ""
set_interface_property pio_in SVD_ADDRESS_GROUP ""

add_interface_port pio_in pio_in pio Input 1


# 
# connection point pio_out
# 
add_interface pio_out conduit end
set_interface_property pio_out associatedClock ""
set_interface_property pio_out associatedReset ""
set_interface_property pio_out ENABLED true
set_interface_property pio_out EXPORT_OF ""
set_interface_property pio_out PORT_NAME_MAP ""
set_interface_property pio_out CMSIS_SVD_VARIABLES ""
set_interface_property pio_out SVD_ADDRESS_GROUP ""

add_interface_port pio_out pio_out pio Output 1

